name: Build BaseApp

on:
  push:
    tags:
      - "*base*"

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [self-hosted-linux]
        arch: [x86_64]
      fail-fast: false
      # Only one job at a time can use the shared repository cache
      max-parallel: 1

    uses: ./.github/workflows/worker.yml
    with:
      ref: ${{ github.ref_name }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
